version: "3"
services:

  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"

  ohmage_test_setup:
    build:
      context: .
      dockerfile: ./test/ohmage_test_setup/Dockerfile
    image: mobilizingcs/pam_ohmage_ohmage_test_setup
    depends_on:
      - ohmage
    environment:
      - OHMAGE_SERVER=ohmage
      - OHMAGE_SERVER_PORT=8080

  pam_ohmage_build:
    volumes:
      - pam_ohmage_build:/pam_ohmage/bin
    build:
      context: .
      dockerfile: ./Dockerfile_Build
    image: mobilizingcs/pam_ohmage_build

  ohmage:
    image: ohmage/server
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - MYSQL_DATABASE=ohmage
      - MYSQL_USER=ohmage
      - MYSQL_PASSWORD=ohmage
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=setmebetter
      - MYSQL_DATABASE=ohmage
      - MYSQL_USER=ohmage
      - MYSQL_PASSWORD=ohmage
volumes:
  pam_ohmage_build: